#!/usr/bin/python3
#jjcli skel > filtro

from jjcli import * 

c=clfilter(opt="do:")     ## option values in c.opt dictionary
dicionarioNomes = set(nomes.strip() for nomes in open("nomes.txt", "r"))
patern = "|".join(dicionarioNomes)

def fs(m):
    return f"@{m[1]}@" if m[1] in dicionarioNomes else m[1] 

for f in c.text():
    f = sub(rf'\b([A-ZÂÁÉ]\w+)\b', fs, f)

    f = sub(r"@\s*@", r" ", f)

    f = sub(r"@\s*(da|do|das|dos|de)\s*@", r" \1 ", f)

    print(f)

